name: Update Classes

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
  repository_dispatch:
    types: [update_class]

jobs:
  classUpdate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Update
        run: npm run classUpdate
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: update classes'
          fetch: true
